# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Specifies the JVM arguments used for the daemon process.
# Added preferIPv4Stack=true to fix UnknownHostException
org.gradle.jvmargs=-Xmx1536m -Djava.net.preferIPv4Stack=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
android.useAndroidX=true

# If you are behind a proxy, uncomment and configure the following lines:
# systemProp.http.proxyHost=your.proxy.host
# systemProp.http.proxyPort=8080
# systemProp.http.proxyUser=user
# systemProp.http.proxyPassword=password
# systemProp.http.nonProxyHosts=localhost|*.example.com

# systemProp.https.proxyHost=your.proxy.host
# systemProp.https.proxyPort=8080
# systemProp.https.proxyUser=user
# systemProp.https.proxyPassword=password
# systemProp.https.nonProxyHosts=localhost|*.example.com
